### ISSUE TITLE
لیبل میلادی

### ISSUE THREAD

**Issue by mostify** [odoo-app-dev/jalaali#2]
![odoo_1](https://user-images.githubusercontent.com/16362791/158057713-471ef3ff-f75c-49a1-815d-0cf03aa89197.PNG)
![odoo_2](https://user-images.githubusercontent.com/16362791/158057715-c5d298ea-bf39-4a7e-81a7-2f06e8d97e79.PNG)

با سلام. طبق عکس در قسمت تاریخچه لیبل تاریخ میلادی هست.
مشکل بعدی هم اینکه زمانی که میخوایم از قسمت فیلتر تاریخی رو فیلتر کنیم سیستم به مشکل بر میخوره که توی عکس دوم مشخص هست.

**Comment by odoo-app-dev** [comment]
سلام
ممنون از وقتی که گذاشتید
نیاز به کار بیشتر روی فایل های جاوا داریم. اگر خودتون یا دوستی رو می شناسید که کمک کنه ممنون میشم معرفی کنید.

**Comment by odoo-app-dev** [comment]
برای حل مشکل لیبل به روش زیر عمل کنید:
1-در فایل 
```
mail/static/src/models/message/message.js
```

تابع
```
_computeDateDay()
```

در آخرین خط این تابع به جای لاین
```
return this.date.format('LL');
```

این عبارت رو وارد کنید:
```
if (session.user_context.lang=='fa_IR'){
    return this.date.format('jYYYY jMMMM jDD');
}else{
    return this.date.format('LL');
}
```

![image](https://user-images.githubusercontent.com/93074385/164895356-73db698f-973b-4b3f-9971-b998f63c6c70.png)
