### ISSUE TITLE
odoo 13 

### ISSUE THREAD

**Issue by nimajv** [odoo-app-dev/jalaali#5]
سلام ، ممنون از اینکه این ماژول رو منتشر کردین، من تونستم رو اودو 13 نصب کنم و طبق راهنما پیش رفتم ، اما بعد از فارسی کردن زبان هم تقویمم  تاریخ های شمسی نشون نمیده باید کار دیگه ای انجام میدادم ؟ یعنی تو کلندر یا ثبت فاکتور باید بتونم تاریخ شمسی ببینم ؟ ممنون میشم راهنماییم کنید

**Comment by odoo-app-dev** [comment]
سلام. 
در حال حاضر فقط روی ادو 15 تست شده.
