### ISSUE TITLE
خطا هنگام باز کردن فیلتر تاریخ

### ISSUE THREAD

**Issue by yaser2490** [odoo-app-dev/jalaali#7]
![Screenshot 2023-01-08 083112](https://user-images.githubusercontent.com/70744366/211181327-e39463de-69a2-4034-8cf0-2cbea30d2114.png)
سلام روی ورژن 15 وقتی میخوام فیلتر تاریخ رو اعمال کنم این خطا میاد کسی راه حلی داره ؟

**Comment by giladoo** [comment]
**_As a workaround you need to add the following snippet after this line:_**

(https://github.com/odoo/odoo/blob/92f54e8e5530a6d010aa03f97310882d30f9e013/addons/web/static/lib/owl/owl.js#L3889)

1. After this line: 

                 `  whyInvalid = whyInvalidProp(props[propName], propsDef[propName]);`

2. Add this code:

```
                     if(Widget.name === 'DateTimePicker' || Widget.name === 'DatePicker' ){
                        whyInvalid = null;
                        }
```
In some older version, you need to add this:

1. After this code:

                   ` isValid = isValidProp(props[propName], propsDef[propName]);`

2. Add this code:

```
                    if(Widget.name === 'DateTimePicker' || Widget.name === 'DatePicker' ){
                        isValid = true;
                        }
```
