### ISSUE TITLE
عدم نمایش تاریخ جلالی در نسخه 16

### ISSUE THREAD

**Issue by alisaeed** [odoo-app-dev/jalaali#8]
سلام و عرض ادب
سپاسگزاریم از بابت زمانی که بابت فارسی سازی ادوو گذاشتید.
من این ماژول را بر روی Odoo 16 نصب کردم اما متاسفانه تاریخ ها به جلالی تغییر نکردند، احتمالا مربوط به تغییرات این نسخه در چند ماه گذشته می باشد. اگر امکان دارد در این زمینه من را راهنمایی بفرمایید.
نسخه 15 با ماژول شما جلالی شد ولی در بعضی موارد مثل پیش نمایش در بخش صدور پیش فاکتور و PDF خروجی آن، تبدیل تاریخ به جلالی صورت نگرفت.

**Comment by odoo-app-dev** [comment]
در حال حاضر فقط برروی ورژن 15 تست شده است. 
برای ورژن 16 هنوز آماده نشده است.
